apiVersion : apps/v1
kind: Deployment
metadata:
  name: michalbidzinskisaplabstask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: michalbidzinskisaplabstask
  template:
    metadata:
      labels:
        app: michalbidzinskisaplabstask 
    spec:
      containers:
        - name: michalbidzinskisaplabstask 
          image: mbidzinsk.azurecr.io/michalbidzinskisaplabstask
          ports:
          - containerPort: 3000