 - apiVersion: v1
  kind: Namespace
  metadata:
    name: rest-api-namespace
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: rest-api
    namespace: rest-api-namespace
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: rest-api
    template:
      metadata:
        labels:
          app: rest-api
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: rest-api
            image: mbidzinsk.azurecr.io/rest-api
            ports:
              - containerPort: 3000

- apiVersion: v1
  kind: Service
  metadata:
    name: rest-api-service
    namespace: rest-api-namespace
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 3000
        name: port3000
        port: 3000
        protocol: TCP
    selector:
      app: rest-api
