apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  type: LoadBalancer
  ports:
    - targerPort: 3000
      port: 3000
      protocol: TCP
  selector:
    app: rest-api
