apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-lang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-lang
  template:
    metadata:
      labels:
        app: github-lang
    spec:
      containers:
        - name: github-lang
          image: mbidzcr.azurecr.io/github-lang
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: github-lang-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 3000
      protocol: TCP
  selector:
    app: github-lang
